### PR TITLE
[JENKINS-58265, 58309, 58467] Added Tag support and minor code refractory

### PR DESCRIPTION
**Pull request by baymac**
## Features:

* Impl `GitLabTagSCMHead`
* Impl `TagDiscoveryTrait`
* Removed extra API calls so faster branch indexing
* Added Tag refspecs in `GitLabSCMBuilder`
* Added Tag strings

## Bugs:

Unable to fetch tags:

Still figuring out the NPE.

Screenshot from 2019-07-12 16-11-30
<details>
<summary>See Text</summary>
Checking tag gitlab-branch-source-v0.0.3-SNAPSHOT
ERROR: [Fri Jul 12 14:22:07 IST 2019] Could not fetch branches from source fc1f3577-d743-43e9-b358-08be8518e2bc
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at io.jenkins.plugins.gitlabbranchsource.GitLabSCMSource$2.close(GitLabSCMSource.java:536)
	at jenkins.scm.api.trait.SCMSourceRequest.process(SCMSourceRequest.java:350)
	at jenkins.scm.api.trait.SCMSourceRequest.process(SCMSourceRequest.java:249)
	at io.jenkins.plugins.gitlabbranchsource.GitLabSCMSource.retrieve(GitLabSCMSource.java:298)
	at jenkins.scm.api.SCMSource._retrieve(SCMSource.java:373)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:283)
	at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:631)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:277)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:164)
	at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:1022)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
[Fri Jul 12 14:22:07 IST 2019] Finished branch indexing. Indexing took 54 sec
FATAL: Failed to recompute children of asdas
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at io.jenkins.plugins.gitlabbranchsource.GitLabSCMSource$2.close(GitLabSCMSource.java:536)
	at jenkins.scm.api.trait.SCMSourceRequest.process(SCMSourceRequest.java:350)
	at jenkins.scm.api.trait.SCMSourceRequest.process(SCMSourceRequest.java:249)
	at io.jenkins.plugins.gitlabbranchsource.GitLabSCMSource.retrieve(GitLabSCMSource.java:298)
	at jenkins.scm.api.SCMSource._retrieve(SCMSource.java:373)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:283)
	at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:631)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:277)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:164)
	at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:1022)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
</details>

### CODE REVIEW

**Comment by baymac** [comment]
The NPE was fixed as the `GitLabSCMFileSystem` did not have appropriate implementation for checking tags. But facing another issue currently [JENKINS-58477](https://issues.jenkins-ci.org/browse/JENKINS-58477).

**Review by markjacksonfishing — APPROVED** [review]
After this PR we move to the new repo correct?

**Comment by baymac** [comment]
@markyjackson-taulia Yes, after 1 more pr which will address webhooks support.

**Comment by baymac** [comment]
Bug for which indexing of tags was not added is fixed:

Screenshot from 2019-07-13 09-32-43

Need to look into why automatic builds for tags are not scheduled.

**Comment by baymac** [comment]
Merging this PR now, will fix [JENKINS-58477](https://issues.jenkins-ci.org/browse/JENKINS-58477) in later sprint.

**Pull request merged**
