### PR TITLE
[JENKINS-58266, 58269, 58455] Hotfix/Subgroups

### PR DESCRIPTION
**Pull request by baymac**
I replaced the variable `projectName` with `projectPath`. The `projectPath` variable contains the path of the project with the namespace (<group>/<subgroup>/<projectName>).

Had to modify the UriTemplates, fixed `doFillProjectPathItems` in GitLabSCMSource, refractored credentials look up in `GitLabSCMSource`.

There is one problem though, it doesn't work when there is a Merge Request in the subgroup project. There is some issue with `BranchDiscoveryTrait`. I am yet to figure out the NPE.

Screenshot from 2019-07-12 09-05-47

### CODE REVIEW

**Comment by jetersen** [comment]
I suggest you attach the debugger and add a debug point on [`BranchDiscoveryTrait:211`](https://github.com/baymac/gitlab-branch-source-plugin/blob/hotfix/subgroups/src/main/java/io/jenkins/plugins/gitlabbranchsource/BranchDiscoveryTrait.java#L211) (next time please include text format, easier to copy&paste)

But my guess is either `m` is `null` or perhaps `getSourceProjectId` is null or perhaps even `getTargetProjectId` is null 😓

**Comment by baymac** [comment]
@casz I am not quite familiar with Jenkins debugging, I generally use `LOGGER.info` for debugging. :sweat_smile:

**Comment by jetersen** [comment]
Intellij adding a mvn hpi:run task and then click debug should do the trick

**Comment by baymac** [comment]
@casz Thanks. I was stuck with `mvnDebug hpi:run`. I didn't know how to attach debugger after that.

**Comment by jetersen** [comment]
image
image
If there was any doubt 😆

**Comment by baymac** [comment]
@casz Whoa! Thanks.

**Comment by baymac** [comment]
So after debugging, I realised `mr.getSourceProjectI()` was null since the source project was deleted. Any suggestion how I should handle this issue?

**Comment by jetersen** [comment]
Cancel the event and logged the reason? :)

**Comment by baymac** [comment]
Okay, will do that.

**Comment by baymac** [comment]
@casz Since the trait will compare different mrs to either exclude branch or not, there is a chance that the desired mr actually has the `source project id` but an mr without `source project id` is encountered will result in an NPE. So when I am adding mrs to the request, I am removing the mrs with `null` source project id in GitLabSCMSource `retrieve(c, o, e, l)`.

```java
List<MergeRequest> mrs = gitLabApi.getMergeRequestApi().getMergeRequests(gitlabProject);
for(MergeRequest mr : mrs) {
     if(mr.getSourceProjectId() == null) {
          mrs.remove(mr);
     }
}
request.setMergeRequests(mrs);
```

**Comment by baymac** [comment]
But now I get this error:

```
Started
[Fri Jul 12 17:57:10 IST 2019] Starting branch indexing...
Looking up project whatabit/subproject/gitlab-api-plugin
Unable to detect if it is a mirror or not still fetching MRs anyway...
ERROR: [Fri Jul 12 17:57:20 IST 2019] Could not fetch branches from source 2c35458b-c652-40ab-8eb7-be587927685d
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at io.jenkins.plugins.gitlabbranchsource.GitLabSCMSource.retrieve(GitLabSCMSource.java:221)
	at jenkins.scm.api.SCMSource._retrieve(SCMSource.java:373)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:283)
	at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:631)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:277)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:164)
	at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:1022)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
[Fri Jul 12 17:57:20 IST 2019] Finished branch indexing. Indexing took 9.4 sec
```

**Comment by baymac** [comment]
From what the exception tells, I understand `one thread is modifying the Collection while another thread is iterating over it`. Hmm.

**Comment by baymac** [comment]
Trying to use stream instead with:
```java
Stream<MergeRequest> mrs = gitLabApi.getMergeRequestApi().getMergeRequestsStream(gitlabProject);
request.setMergeRequests(mrs.filter(mr -> mr.getSourceProjectId() != null)::iterator);
```

But again error:
```
Checking branches.. 
Checking branch develop
      ‘Jenkinsfile’ found
Met criteria
Scheduled build for branch: develop
Checking branch master
ERROR: [Fri Jul 12 18:12:02 IST 2019] Could not fetch branches from source ee671716-2ab9-4706-b4a3-bb9e67e06a69
java.lang.IllegalStateException: stream has already been operated upon or closed
	at java.util.stream.AbstractPipeline.spliterator(AbstractPipeline.java:343)
	at java.util.stream.ReferencePipeline.iterator(ReferencePipeline.java:139)
	at io.jenkins.plugins.gitlabbranchsource.BranchDiscoveryTrait$ExcludeOriginMRBranchesSCMHeadFilter.isExcluded(BranchDiscoveryTrait.java:209)
	at jenkins.scm.api.trait.SCMSourceRequest.isExcluded(SCMSourceRequest.java:196)
	at jenkins.scm.api.trait.SCMSourceRequest.process(SCMSourceRequest.java:333)
	at jenkins.scm.api.trait.SCMSourceRequest.process(SCMSourceRequest.java:286)
	at io.jenkins.plugins.gitlabbranchsource.GitLabSCMSource.retrieve(GitLabSCMSource.java:247)
	at jenkins.scm.api.SCMSource._retrieve(SCMSource.java:373)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:283)
	at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:631)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:277)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:164)
	at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:1022)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```

Which is obvious because Stream is consumed when first branch `develop` was processed. :man_facepalming:

**Comment by baymac** [comment]
Now it works with:

```java
List<MergeRequest> mrs = gitLabApi.getMergeRequestApi().getMergeRequests(gitlabProject);
mrs = mrs.stream().filter(mr -> mr.getSourceProjectId() != null).collect(Collectors.toList());
request.setMergeRequests(mrs);
```

**Pull request merged**
