### PR TITLE
[JENKINS-58400] Feature/pipeline status

### PR DESCRIPTION
**Pull request by baymac**
Implementation of GitLab Build Status Notifier. It works in a way that it returns result to GitLab Server about the commit status but it logs some error which I am still figuring out.

```
org.gitlab4j.api.GitLabApiException: Cannot transition status via :enqueue from :pending (Reason(s): Status cannot transition via "enqueue")
        at org.gitlab4j.api.AbstractApi.validate(AbstractApi.java:593)
        at org.gitlab4j.api.AbstractApi.post(AbstractApi.java:264)
        at org.gitlab4j.api.CommitsApi.addCommitStatus(CommitsApi.java:452)
        at io.jenkins.plugins.gitlabbranchsource.helpers.GitLabSCMBuildStatusPublisher.sendNotifications(GitLabSCMBuildStatusPublisher.java:126)
        at io.jenkins.plugins.gitlabbranchsource.helpers.GitLabSCMBuildStatusPublisher.access$200(GitLabSCMBuildStatusPublisher.java:48)
        at io.jenkins.plugins.gitlabbranchsource.helpers.GitLabSCMBuildStatusPublisher$JobCheckOutListener.onCheckout(GitLabSCMBuildStatusPublisher.java:241)
        at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:136)
        at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:90)
        at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:77)
        at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

### CODE REVIEW

**Review by markjacksonfishing — APPROVED** [review]
lgtm also thank you for including the jira ticket number

**Comment by baymac** [comment]
> lgtm also thank you for including the jira ticket number

It feels good to get back to Agile. Last development cycle was a pain for all of us. :sweat_smile:

**Comment by baymac** [comment]
I think we can go ahead and merge this pr. The error logs can be revisited later. Rn pipeline status is correctly notified to the GitLab Server. Can you guys test it on your machine and confirm?

**Comment by jetersen** [comment]
Have you tested notificationsDisabled trait?

**Comment by jetersen** [comment]
regarding `:enqueue` I suggest you take a look here: https://github.com/JetBrains/commit-status-publisher/tree/master/commit-status-publisher-server/src/main/java/jetbrains/buildServer/commitPublisher/gitlab for gitlab specific commit status publishing :)

**Comment by baymac** [comment]
> Have you tested notificationsDisabled trait?

Yes it works with Notification Disabled. But I don't think we have a Notification Disabled trait for user. In the code, if I get the `GitLabSCMSourceContext` with NotificationsDisabled.

```java
private static void sendNotifications(Run<?, ?> build, TaskListener listener)
            throws IOException, InterruptedException {

        final SCMSource s = SCMSource.SourceByItem.findSource(build.getParent());
        if (!(s instanceof GitLabSCMSource)) {
            return;
        }
        GitLabSCMSource source = (GitLabSCMSource) s;
        final GitLabSCMSourceContext sourceContext = new GitLabSCMSourceContext(null, SCMHeadObserver.none())
                .withTraits((source.getTraits())).withNotificationsDisabled(true);
        if (sourceContext
                .notificationsDisabled()) {
            return;
        }
        ....
```
Jenkins doesn't notify GitLab about the build status. Should I add a trait specific to that?

**Comment by jetersen** [comment]
No, the notification trait should come from an extension plugin in my opinion.

I know one exists for bitbucket branch source plugin: https://wiki.jenkins.io/display/JENKINS/Skip+Notifications+Trait+Plugin perhaps it could be expanded to support other branch source plugins.
See these plugins for multiple trait support: 
https://github.com/jenkinsci/scm-trait-commit-skip-plugin
https://github.com/jenkinsci/scm-filter-aged-refs-plugin
https://github.com/jenkinsci/scm-filter-jira-validator-plugin

**Comment by baymac** [comment]
Can we add GitLab skip notification trait to `skip-notifications-trait-plugin` or we need to create a new plugin for that? @casz

**Comment by baymac** [comment]
@markyjackson-taulia @casz I fixed the `enqueue` error. I made a mistake of changing the status of an already `pending` pipeline to a `pending` again when build started. Changed it to `running`. I think all pipeline statuses are now appropriate.

**Review by markjacksonfishing — APPROVED** [review]
Nice change @baymac this looks good.

**Comment by jetersen** [comment]
I think it would be best added to skip-notifications-trait-plugin

**Comment by baymac** [comment]
There is a confusion on the format of pipeline status.

Case I:

GitLab Pipeline status is not similar to GitHub (where it is a simple boolean field). GitLab Pipeline status are similar to Jenkins Pipeline and has stages. For example,

It contains
* `#1 Declarative checkout passed`
* `#2 Stage 1 passed`

This can be seen in the following screenshot.
Screenshot from 2019-07-11 11-20-01
This is how it is implemented in [ArgelBargel's GitLab Branch Source Plugin](https://github.com/Argelbargel/gitlab-branch-source-plugin/).

The problem:

1. If the job is canceled. The stage details is not passed on to the Pipeline Status. It doesn't provide appropriate details. Below is the screenshot of that.

Screenshot from 2019-07-11 11-23-51

The `Stage 1` failed but GitLab Pipeline is not notified about it.

2. All the stages link to the build. Meaning they don't link to their respective stages because Jenkins doesn't have a dedicated action for stages. You can only have a popup menu to see the log of a particular stage.

Case II:

This is what I have implemented. We are notifiy GitLab pipeline about the Job status instead of Pipeline stages.

Screenshot from 2019-07-11 11-12-47

This is done with following assumptions:

1. GitLab User doesn't change the job name for the same project. You can see multiple pipeline statuses for a single pipeline status as they are made by different jobs.

2. GitLab User goes to Jenkins to see the stages details rather than GitLab itself.

If the above assumptions are wrong then it can be problems. Let me know your thoughts.

**Comment by justinharringa** [comment]
> There is a confusion on the format of pipeline status.
> 
> Case I:
> 
> GitLab Pipeline status is not similar to GitHub (where it is a simple boolean field). GitLab Pipeline status are similar to Jenkins Pipeline and has stages. For example,
> 
> It contains
> 
> * `#1 Declarative checkout passed`
> * `#2 Stage 1 passed`
> 
> This can be seen in the following screenshot.
> Screenshot from 2019-07-11 11-20-01
> This is how it is implemented in [ArgelBargel's GitLab Branch Source Plugin](https://github.com/Argelbargel/gitlab-branch-source-plugin/).
> 
> The problem:
> 
> 1. If the job is canceled. The stage details is not passed on to the Pipeline Status. It doesn't provide appropriate details. Below is the screenshot of that.
> 
> Screenshot from 2019-07-11 11-23-51
> 
> The `Stage 1` failed but GitLab Pipeline is not notified about it.
> 
> 1. All the stages link to the build. Meaning they don't link to their respective stages because Jenkins doesn't have a dedicated action for stages. You can only have a popup menu to see the log of a particular stage.
> 
> Case II:
> 
> This is what I have implemented. We are notifiy GitLab pipeline about the Job status instead of Pipeline stages.
> 
> Screenshot from 2019-07-11 11-12-47
> 
> This is done with following assumptions:
> 
> 1. GitLab User doesn't change the job name for the same project. You can see multiple pipeline statuses for a single pipeline status as they are made by different jobs.
> 2. GitLab User goes to Jenkins to see the stages details rather than GitLab itself.
> 
> If the above assumptions are wrong then it can be problems. Let me know your thoughts.

I suspect that this is because GitLab also has CI and the GitLab CI stages would show up there. Perhaps it would be nice to provide the option for the user to just get the overall status vs stages?

BTW, GitHub has a new [Checks](https://developer.github.com/v3/checks/) API which does something similar.

**Comment by baymac** [comment]
@justinharringa thanks for the suggestion. Yes, I also feel it would nice to provide user with the option of that. This will require a considerable amount to work compared to other bugs that are there in the plugin. Once I fix them I will start working on this. :metal:

**Pull request merged**
