### PR TITLE
[JENKINS-58318] Hotfix/gitlab group

### PR DESCRIPTION
**Pull request by baymac**
The `GitLabSCMNavigator` Impl had some issues with the branch indexing as the project wasn't fetched properly. Also it accepted `serverUrl`, now it accepts `serverName`. These issues are fixed in this pr.

There is only problem though, which is the SCM traits are not working as expected. When you create a `GitLab Group` job it should create 3 default `SCMTraits` similar to `Multibranch Pipeline Jobs`. (See GitLabSCMNavigator DescriptorImpl). But the traits do not get loaded as expected. Even when you add the traits (or Behaviours), branch indexing doesn't work accordingly. 

For example,

I add
* Discover Branches
* Discover Merge Requests from Origin

The branch indexing does not consider Merge Requests. This is suprising because it delegates the task to `GitLabSCMSource` for the indexing job. While `GitLabSCMSource` works as expected, `GitLabSCMNavigator` doesn't.

### CODE REVIEW

**Review by markjacksonfishing — APPROVED** [review]

**Comment by baymac** [comment]
The default list of SCMTraits in GitLabSCMNavigator is fixed. The problem remains is the log doesn't show the SCMSources builds, although it happens it the background based on the SCM Traits.

Here's an example, I am performing a GitLab Group Job (with default traits) on my user account with 2 repositories.

Screenshot from 2019-07-11 20-04-30

In the above log it can be seen for`gitlab-branch-source-plugin` project only 1 branch was processed.

But behind the scenes, `GitLabSCMSource` processes all the necessary branches based on default SCM Traits.

Screenshot from 2019-07-11 20-04-39

**Comment by baymac** [comment]
Merging this pr now. The current issue with GitLabSCMNavigator is tracked here [JENKINS-58446](https://issues.jenkins-ci.org/browse/JENKINS-58446)

**Comment by justinharringa** [comment]
> The default list of SCMTraits in GitLabSCMNavigator is fixed. The problem remains is the log doesn't show the SCMSources builds, although it happens it the background based on the SCM Traits.
> 
> Here's an example, I am performing a GitLab Group Job (with default traits) on my user account with 2 repositories.
> 
> Screenshot from 2019-07-11 20-04-30
> 
> In the above log it can be seen for`gitlab-branch-source-plugin` project only 1 branch was processed.
> 
> But behind the scenes, `GitLabSCMSource` processes all the necessary branches based on default SCM Traits.
> 
> Screenshot from 2019-07-11 20-04-39

I wonder if this is some kind of container object which holds onto the list somehow? Very strange. Perhaps debugging would reveal the object graph and where the `1` is coming from. I can poke at this a bit sometime this week if you haven't figured this out.

**Comment by baymac** [comment]
@justinharringa Thanks. I will look into this and if by the weekend I am unable to figure it out. I will let you, please take a look, it will be very helpful.

**Pull request merged**
