### PR TITLE
[JENKINS-57889] Add HashMap for GitLab filter methods

### PR DESCRIPTION
**Pull request by baymac**
1. Added a hashmap that stores (name, server) key, value pair. Kept it transient so that we do not have to serialize it. But the problem is you cannot populate the HashMap in the constructore as some JCasC rules error. Maybe @casz can englighten what is going wrong.

2. Some minor documentation changes

3. Removed gitlab server warnings because a URI check scheme with gitlab might not work. See https://github.com/gitlab4j/gitlab4j-api/issues/384. I haven't been able to figure a way to validate a gitlab server url without authentication yet.

### CODE REVIEW

**Comment by baymac** [comment]
Removed serverMap from transient. That might solve the problem but there will be overhead of serialising the map as well. I hope that will be fine if it saves user's time.

**Comment by jetersen** [comment]
Could you share the exception?

But as I recall, Map is not supported: https://github.com/jenkinsci/configuration-as-code-plugin/pull/900

**Comment by baymac** [comment]
You can see the error in the test results - https://gist.github.com/baymac/c26381fa04797c377fd94f4986a740f4

**Comment by baymac** [comment]
You can also reproduce yourself by commenting out the `refreshServerMap` method in the `GitLabServer` constructor.

**Comment by jetersen** [comment]
@baymac CI says otherwise, did you forget to do an `mvn clean`?

**Comment by baymac** [comment]
The test passes in CI because the code that has been pushed, the constructor doesn't have the `refreshServerMap` method. Only when you include this method in the GitLabServers constructor you see the above error.

**Review by jetersen — COMMENTED** [review]
Regarding using a hashmap, I feel like your pre-optimizing for a use case that is never going to be relevant. Most users will have two servers, gitlab.com, and their private instance.
With 10 or 100 servers in the list, even though that will most likely be an unrealistic scenario, an array lookup is still going to be pretty fast.

**Comment by baymac** [comment]
In a case where there is big team and they all want to setup a server for each of their user to manage webhooks on the project they created, there will be multiple instances of server entries. I think if it is not causing compatibility issues we can benefit from hashmaps.

**Comment by baymac** [comment]
* Added a method `removeDuplicateServers` which gets called inside `configure`. I have also added logging so that you can see that server names with duplicate names are removed.

* Modified `refreshServerMap` method to use Java 8 streams.

The problem I am still having is that `servers` list saves only the distinct objects (see logs) but the same is not reflected in the UI. The UI still has servers with the duplicate names. Only after Jenkins restart the UI changes occur. Is there a way to refresh the UI to reload the elements at runtime?

**Comment by jetersen** [comment]
On a big team they would use an individual Jenkins instance as well :sweat:
Also usually most people have a CI user that they can just give access to their projects.

**Comment by baymac** [comment]
Okay, I get it now. I am closing this PR. Can you review #16?

**Pull request closed without merging**
